index:
    path: /
    controller: App\Controller\HomeController::index


register:
    path: /register
    controller: App\Controller\SecurityController::register

events_list:
    path: /events/list
    controller: App\Controller\EventsController::index

create_event:
    path: /events/new
    controller: App\Controller\EventsController::new

event_details:
    path: /event/{id}/details
    controller: App\Controller\EventsController::show

event_delete:
    path: /event/delete/{id}
    controller: App\Controller\EventsController::delete



